### ISSUE TITLE
Inventory and decide on first sprint of ET supplemental data sources

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/Evapotranspiration#1]

**Comment by xinshizheng** [comment]
I will look into Land Cover (NAIP) and Forecasted ET from NOAA. Hongting will look into Precipitation, Temperature and Wind data

**Comment by patwater** [comment]
Sounds great!  @gcortesla can provide great detail on NAIP and note that will require more than a tabular data parse to integrate so NAIP is a longer term lift.  Brianna Pagan (in Gonzalo's lab at UCLA) speaks highly of the Forecasted ET from NOAA.

**Comment by xinshizheng** [comment]
@patwater @gcortesla Can I know why we want to incorporate the Forecasted ET (FRET) from NOAA? Is it going to be used for model result validation/calibration, or it is going to be added to the existing CIMIS product/services as an additional map? I have spent a few hours navigating the NOAA website for it and found that it can be downloaded from the links on the page: http://www.nws.noaa.gov/os/notification/scn16-08fretcca.htm. The data will be in Gridded Binary Version 2 (GRIB2) format and requires the installation of a Windows-based package DEGRIB (http://www.weather.gov/mdl/degrib_download). Otherwise it can be accessed as a static graph, as mentioned on the first link above. The data will contain following components:
- Daily FRET grids for the next 7 days
- Total Weekly FRET grids for the 7-day period
- Daily FRET departure from normal grids

My question is that should I continue looking into the FRET data? Let me know what you think.

**Comment by christophertull** [comment]
My sense is that it is certainly interesting and useful for us, but maybe a little bit of a digression from the core project? Seems most applicable to the demand forecasting, less so for the longterm framework.

**Comment by gcortesla** [comment]
I agree with @christophertull. The NOAA FRET will be more useful once we have implemented our own ET estimation framework, as we would be able to compare our own future forecasts with the NOAA forecasts.

**Comment by xinshizheng** [comment]
That makes sense. @gcortesla do you have any suggestions on NAIP data? The most updated  (2016) NAIP data source I found is the Geospatial Data Gateway by USDA (https://gdg.sc.egov.usda.gov/GDGOrder.aspx). However, the data can only be downloaded county by county since for the whole California the size is around 111 GB. Any advice?

**Comment by gcortesla** [comment]
@xinshizheng I suggest working with the USGS Earth Explorer: https://earthexplorer.usgs.gov/. There you can download square tiles of NAIP data instead of county-wise data. I have already downloaded tiles for Los Angeles county, let me handle NAIP in the meantime as it will take an enormous amount of storage space to download and process all of them.
